[package]
name = "rdx"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.14"
env_logger = "0.9.0"

winit = "0.25.0"

erupt = "0.19.0"
gpu-alloc = "0.5.2"
gpu-alloc-erupt = "0.5.0"

parking_lot = "0.11.2"

glam = "0.20.0"

memoffset = "0.6.4"