[package]
name = "tracer"
version = "0.1.0"
authors = ["Gonçalo Soares <goncalofds@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
bevy = { version = "0.5" , default-features = false, features = ["bevy_winit"]}
tracer_render = { path = "./crates/tracer_render" }
glam = { version = "0.16", features = ["transform-types"] }

[build-dependencies]
spirv-builder = { git = "https://github.com/EmbarkStudios/rust-gpu" }
